platform :ios , '7.0'
target 'Travel' do
    
    #=========================================================
    #======================== Lib Dependency =================
    #=========================================================
    pod 'ChatKit','0.8.9'
    #=========================================================
    #======================== Demo Dependency ================
    #=========================================================
    pod 'AVOSCloud', '~> 3.8.0'
    pod 'MBProgressHUD'
    pod 'CYLTabBarController'
    pod 'TWMessageBarManager'
    #pod "FDStackView", "1.0"
    pod 'MWPhotoBrowser'
    pod 'MLPAutoCompleteTextField'
    pod 'SDWebImage','3.8.2'
    #pod 'HYBMasonryAutoCellHeight','~> 2.0.1'
    pod 'ZFPlayer'
    pod 'YYKit'
    pod 'KVOController'
    pod 'TSUIKit'
    pod 'TSMessages'
    pod 'Masonry'
    
end
